"use client";
import { useState } from "react";

type Evidence = { claim: string; metricName?: string; matchId?: string; roundNumber?: number };
type Answer = { conclusion: string; confidence: string; playerEvidence: Evidence[]; recommendations: Array<{ action: string; rationale: string }>; limitations: string[]; nextQuestions: string[] };
type Usage = { inputTokens: number; outputTokens: number; totalTokens: number; estimatedCostUsd: number | null };
type Result = { runId: string; answer: Answer; usage?: Usage };
type Trace = { status: string; steps: number; toolNames: string[]; usage: Usage };
type Match = { matchId: string; mapName: string; playedAt: string; result: "win" | "loss" };
type AnalysisMode = "recent" | "match";
const recentPresets = [{ label: "近期趋势", question: "我最近的状态变好了吗？" }, { label: "攻守差异", question: "我的攻守方表现有什么差异？" }, { label: "首死问题", question: "我为什么经常成为首死？" }, { label: "地图表现", question: "我在不同地图的表现如何？" }];
const matchPresets = [{ label: "整局总结", question: "总结这场比赛最值得复盘的问题" }, { label: "关键问题", question: "这场比赛我最需要改进什么？" }, { label: "数据复盘", question: "结合数据复盘这场比赛" }];

function formatMatchDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date);
}

export function AgentDemo() {
  const [loggedIn, setLoggedIn] = useState(false); const [mode, setMode] = useState<AnalysisMode>("recent"); const [question, setQuestion] = useState(recentPresets[0].question);
  const [matches, setMatches] = useState<Match[]>([]); const [selectedMatchId, setSelectedMatchId] = useState("");
  const [result, setResult] = useState<Result | null>(null); const [trace, setTrace] = useState<Trace | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function loadMatches() { const response = await fetch("/api/matches?limit=6"); const payload = await response.json(); if (!response.ok) return setError(payload.message ?? "无法读取比赛列表。"); const items = payload.matches as Match[]; setMatches(items); if (items[0]) setSelectedMatchId((current) => current || items[0].matchId); }
  async function demoLogin() { setLoading(true); setError(null); const response = await fetch("/api/auth/demo", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setLoading(false); if (!response.ok) return setError((await response.json()).message ?? "Demo 登录失败"); setLoggedIn(true); await loadMatches(); }
  function changeMode(nextMode: AnalysisMode) { setMode(nextMode); setQuestion(nextMode === "recent" ? recentPresets[0].question : matchPresets[0].question); setResult(null); setTrace(null); setError(null); }
  async function analyze() { setLoading(true); setError(null); setResult(null); setTrace(null); const scope = mode === "match" ? { type: "match", matchId: selectedMatchId } : { type: "recent" }; const response = await fetch("/api/agent/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question, scope }) }); const payload = await response.json(); setLoading(false); if (!response.ok) return setError(payload.message ?? "分析失败，请重试。"); setResult(payload); }
  async function loadTrace() { if (!result) return; const response = await fetch(`/api/agent/runs/${result.runId}`); const payload = await response.json(); if (!response.ok) return setError(payload.message ?? "无法读取本次运行记录。"); setTrace(payload); }
  const presets = mode === "recent" ? recentPresets : matchPresets;
  const selectedMatch = matches.find((item) => item.matchId === selectedMatchId);
  return <main className="app-shell"><nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">V</span>VALORANT <em>ANALYTICS</em></a><span className="session-status"><i />{loggedIn ? "DEMO 已连接" : "赛后分析 Agent"}</span></nav>
    <section className="hero" id="top"><p className="eyebrow">国际服竞技 · 个人赛后复盘</p><h1>从对局中，找到<br />下一个突破口。</h1><p>围绕最近表现或某一场比赛提问，Agent 只使用你的结构化赛后数据和具体回合证据。</p></section>
    <section className="workspace">{!loggedIn ? <div className="login-panel"><div><small>DEMO FIXTURE</small><h2>用脱敏比赛数据体验完整分析</h2><p>登录固定 Demo 账号，不需要 Riot 凭据，也不能查询其他玩家。</p></div><button className="primary" disabled={loading} onClick={demoLogin}>{loading ? "正在连接…" : "进入 Demo"}<b>→</b></button></div> : <><div className="scope-tabs"><button className={mode === "recent" ? "active" : ""} onClick={() => changeMode("recent")}><b>最近场次分析</b><span>寻找跨场趋势和重复问题</span></button><button className={mode === "match" ? "active" : ""} onClick={() => changeMode("match")}><b>单局比赛复盘</b><span>选定一场比赛深入分析</span></button></div>{mode === "match" && <div className="match-picker"><header><b>选择一场最近的竞技比赛</b><span>{matches.length} 场可选</span></header><div>{matches.map((item) => <button key={item.matchId} className={selectedMatchId === item.matchId ? "active" : ""} onClick={() => setSelectedMatchId(item.matchId)}><span><b>{item.mapName}</b><small>{formatMatchDate(item.playedAt)}</small></span><em className={item.result}>{item.result === "win" ? "胜利" : "失利"}</em></button>)}</div></div>}<div className="question-panel"><div className="scope-note"><b>{mode === "recent" ? "分析最近完成的竞技场次" : `${selectedMatch?.mapName ?? "所选比赛"} · 单局范围`}</b><span>{mode === "recent" ? "Agent 可比较趋势、地图、攻守和首死问题" : "Agent 不会混入其他比赛数据"}</span></div><label htmlFor="question">你想复盘什么？</label><div className="composer"><textarea id="question" value={question} onChange={(event) => setQuestion(event.target.value)} rows={2} /><button className="primary" disabled={loading || !question.trim() || (mode === "match" && !selectedMatchId)} onClick={analyze}>{loading ? "分析中…" : "开始分析"}<b>↗</b></button></div><div className="presets">{presets.map((preset) => <button className={question === preset.question ? "active" : ""} key={preset.label} onClick={() => setQuestion(preset.question)}>{preset.label}</button>)}</div></div></>}{error && <div className="error"><div><b>请求未完成</b><p>{error}</p></div><button onClick={loggedIn ? analyze : demoLogin} disabled={loading}>重试</button></div>}</section>
    {result && <section className="results"><header><div><i />分析结果</div><span>{mode === "recent" ? "最近场次" : selectedMatch?.mapName ?? "单局比赛"}</span></header><div className="analysis-summary"><article><small>核心结论</small><h2>{result.answer.conclusion}</h2></article><aside><span>{result.answer.playerEvidence.length}<small>证据条目</small></span><span>{result.answer.recommendations.length}<small>行动建议</small></span></aside></div><section className="evidence-list"><header><b>关键证据</b><span>指标与比赛 / 回合引用</span></header>{result.answer.playerEvidence.length ? result.answer.playerEvidence.map((item, index) => <article key={`${item.claim}-${index}`}><i>{String(index + 1).padStart(2, "0")}</i><p><b>{item.claim}</b><span>{item.metricName ?? `${item.matchId} · 第 ${item.roundNumber} 回合`}</span></p></article>) : <p>当前没有足够的个人比赛证据。</p>}</section><section className="recommendations"><header><b>下一步怎么练</b></header>{result.answer.recommendations.map((item, index) => <article key={`${item.action}-${index}`}><i>{index + 1}</i><p><b>{item.action}</b><span>{item.rationale}</span></p></article>)}</section><div className="details"><section><small>数据限制</small>{result.answer.limitations.map((item) => <p key={item}>— {item}</p>)}</section><section><small>继续追问</small>{result.answer.nextQuestions.map((item) => <button key={item} onClick={() => { setQuestion(item); window.scrollTo({ top: 0, behavior: "smooth" }); }}>{item}</button>)}</section></div><div className="trace"><div><small>运行诊断</small><b>{trace ? `${trace.status.toUpperCase()} · ${trace.steps} STEPS · ${trace.toolNames.join(" / ") || "NO TOOL"}` : `RUN ${result.runId.slice(0, 8)} · ${result.usage?.totalTokens ?? 0} TOKENS`}</b></div><button onClick={loadTrace}>{trace ? "已加载" : "展开 Trace"}</button></div></section>}
  </main>;
}
