"use client";
import { useEffect, useState } from "react";

type Evidence = { claim: string; metricName?: string; matchId?: string; roundNumber?: number };
type Answer = { conclusion: string; confidence: string; playerEvidence: Evidence[]; recommendations: Array<{ action: string; rationale: string }>; limitations: string[]; nextQuestions: string[] };
type Usage = { inputTokens: number; outputTokens: number; totalTokens: number; estimatedCostUsd: number | null };
type Result = { runId: string; answer: Answer; usage?: Usage };
type Trace = { status: string; steps: number; toolNames: string[]; usage: Usage };
type Match = { matchId: string; mapName: string; playedAt: string; result: "win" | "loss" };
type Memory = { id: string; kind: "goal" | "summary"; content: string; sourceRunId?: string };
type SyncJob = { jobId: string; status: "queued" | "running" | "completed" | "failed"; imported: number; skipped: number; failedMatchIds: string[]; errorMessage?: string };
type Benchmark = { available: boolean; tier: number | null; cohortPlayers: number; minimumPlayers: number; player: { kd: number; adr: number; acs: number; firstDeathRate: number } | null; median: { kd: number; adr: number; acs: number; firstDeathRate: number } | null; limitation?: string };
type AnalysisMode = "recent" | "match";
const recentPresets = [{ label: "近期趋势", question: "我最近的状态变好了吗？" }, { label: "攻守差异", question: "我的攻守方表现有什么差异？" }, { label: "首死问题", question: "我为什么经常成为首死？" }, { label: "地图表现", question: "我在不同地图的表现如何？" }];
const matchPresets = [{ label: "整局总结", question: "总结这场比赛最值得复盘的问题" }, { label: "关键问题", question: "这场比赛我最需要改进什么？" }, { label: "数据复盘", question: "结合数据复盘这场比赛" }];

function formatMatchDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date);
}

export function AgentDemo() {
  const [loggedIn, setLoggedIn] = useState(false); const [accountMode, setAccountMode] = useState<"demo" | "riot" | null>(null); const [mode, setMode] = useState<AnalysisMode>("recent"); const [question, setQuestion] = useState(recentPresets[0].question);
  const [matches, setMatches] = useState<Match[]>([]); const [selectedMatchId, setSelectedMatchId] = useState("");
  const [result, setResult] = useState<Result | null>(null); const [trace, setTrace] = useState<Trace | null>(null); const [benchmark, setBenchmark] = useState<Benchmark | null>(null); const [memories, setMemories] = useState<Memory[]>([]); const [memoryDraft, setMemoryDraft] = useState(""); const [memoryKind, setMemoryKind] = useState<Memory["kind"]>("goal"); const [syncJob, setSyncJob] = useState<SyncJob | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [savingSummary, setSavingSummary] = useState(false); const [savedSummaryRunId, setSavedSummaryRunId] = useState<string | null>(null);
  async function jsonRequest(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, cache: "no-store" }); const payload = response.status === 204 ? null : await response.json(); return { response, payload }; }
  async function loadMatches() { const response = await fetch("/api/matches?limit=6"); const payload = await response.json(); if (!response.ok) return setError(payload.message ?? "无法读取比赛列表。"); const items = payload.matches as Match[]; setMatches(items); if (items[0]) setSelectedMatchId((current) => current || items[0].matchId); }
  async function loadAccountData() { await Promise.all([loadMatches(), jsonRequest("/api/benchmark").then(({ response, payload }) => { if (response.ok) setBenchmark(payload); }), jsonRequest("/api/memory").then(({ response, payload }) => { if (response.ok) setMemories(payload.memories ?? []); })]); }
  useEffect(() => { void jsonRequest("/api/auth/status").then(({ response, payload }) => { if (response.ok && payload.authenticated && payload.connected) { setLoggedIn(true); setAccountMode(payload.mode); void loadAccountData(); } }); }, []);
  async function demoLogin() { setLoading(true); setError(null); const { response, payload } = await jsonRequest("/api/auth/demo", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setLoading(false); if (!response.ok) return setError(payload?.message ?? "Demo 登录失败"); setLoggedIn(true); setAccountMode("demo"); await loadAccountData(); }
  function connectRiot() { window.location.href = "/api/auth/riot/start"; }
  async function disconnectAccount() { setLoading(true); setError(null); const { response, payload } = await jsonRequest("/api/auth/riot/disconnect", { method: "POST" }); setLoading(false); if (!response.ok) return setError(payload?.message ?? "断开账号失败。"); setLoggedIn(false); setAccountMode(null); setMatches([]); setMemories([]); setBenchmark(null); setResult(null); setTrace(null); setSyncJob(null); setSavedSummaryRunId(null); }
  async function syncMatches() { setLoading(true); setError(null); const { response, payload } = await jsonRequest("/api/sync", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); if (!response.ok) { setLoading(false); return setError(payload?.message ?? "同步未能启动。"); } let current = payload as SyncJob; setSyncJob(current); for (let attempt = 0; attempt < 25 && (current.status === "queued" || current.status === "running"); attempt += 1) { await new Promise((resolve) => window.setTimeout(resolve, 800)); const next = await jsonRequest(`/api/sync/${current.jobId}`); if (!next.response.ok) break; current = next.payload as SyncJob; setSyncJob(current); } setLoading(false); if (current.status === "failed") setError(current.errorMessage ?? "比赛同步失败。"); else await loadAccountData(); }
  function changeMode(nextMode: AnalysisMode) { setMode(nextMode); setQuestion(nextMode === "recent" ? recentPresets[0].question : matchPresets[0].question); setResult(null); setTrace(null); setError(null); }
  async function analyze() { setLoading(true); setError(null); setResult(null); setTrace(null); setSavedSummaryRunId(null); const scope = mode === "match" ? { type: "match", matchId: selectedMatchId } : { type: "recent" }; const response = await fetch("/api/agent/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question, scope }) }); const payload = await response.json(); setLoading(false); if (!response.ok) return setError(payload.message ?? "分析失败，请重试。"); setResult(payload); }
  async function saveAnalysisSummary() { if (!result || savedSummaryRunId === result.runId) return; setSavingSummary(true); setError(null); const { response, payload } = await jsonRequest("/api/memory", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: "summary", content: result.answer.conclusion, sourceRunId: result.runId }) }); setSavingSummary(false); if (!response.ok) return setError(payload?.message ?? "保存分析摘要失败。"); setMemories((items) => [payload, ...items]); setSavedSummaryRunId(result.runId); }
  async function loadTrace() { if (!result) return; const response = await fetch(`/api/agent/runs/${result.runId}`); const payload = await response.json(); if (!response.ok) return setError(payload.message ?? "无法读取本次运行记录。"); setTrace(payload); }
  async function addMemory() { if (!memoryDraft.trim()) return; const { response, payload } = await jsonRequest("/api/memory", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: memoryKind, content: memoryDraft }) }); if (!response.ok) return setError(payload?.message ?? "保存记忆失败。"); setMemories((items) => [payload, ...items]); setMemoryDraft(""); }
  async function editMemory(memory: Memory) { const { response, payload } = await jsonRequest(`/api/memory/${memory.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: memory.kind, content: memory.content }) }); if (!response.ok) return setError(payload?.message ?? "更新记忆失败。"); setMemories((items) => items.map((item) => item.id === memory.id ? payload : item)); }
  async function deleteMemory(id: string) { const { response, payload } = await jsonRequest(`/api/memory/${id}`, { method: "DELETE" }); if (!response.ok) return setError(payload?.message ?? "删除记忆失败。"); setMemories((items) => items.filter((item) => item.id !== id)); }
  const presets = mode === "recent" ? recentPresets : matchPresets;
  const selectedMatch = matches.find((item) => item.matchId === selectedMatchId);
  function continueQuestion(nextQuestion: string) {
    setQuestion(nextQuestion);
    const input = document.getElementById("question") as HTMLTextAreaElement | null;
    input?.scrollIntoView({ block: "center", behavior: "smooth" });
    window.setTimeout(() => input?.focus(), 250);
  }
  return <main className="app-shell"><nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">V</span>VALORANT <em>ANALYTICS</em></a><span className="session-status"><i />{loggedIn ? `${accountMode === "demo" ? "DEMO" : "RIOT"} 已连接` : "赛后分析 Agent"}</span></nav>
    <section className="hero" id="top"><p className="eyebrow">国际服竞技 · 个人赛后复盘</p><h1>从对局中，找到<br />下一个突破口。</h1><p>围绕最近表现或某一场比赛提问，Agent 只使用你的结构化赛后数据和具体回合证据。</p></section>
    <section className="workspace">{!loggedIn ? <div className="login-panel"><div><small>审核演示版本</small><h2>用脱敏比赛数据体验完整分析</h2><p>Demo 不需要 Riot 凭据；上线账号通过 Riot Sign On 只读取你自己的已完成竞技比赛。</p></div><div className="login-actions"><button className="primary" disabled={loading} onClick={demoLogin}>{loading ? "正在连接…" : "进入 Demo"}<b>→</b></button><button className="secondary" onClick={connectRiot}>使用 Riot 账号登录</button></div></div> : <><div className="account-toolbar"><span>{accountMode === "demo" ? "固定脱敏账号" : "Riot 授权账号"}</span><button onClick={syncMatches} disabled={loading}>{loading ? "同步中…" : "同步最近比赛"}</button></div>{syncJob && <p className="sync-status">同步状态：{syncJob.status} · 已导入 {syncJob.imported} 场 · 跳过 {syncJob.skipped} 场{syncJob.failedMatchIds.length ? ` · ${syncJob.failedMatchIds.length} 场失败待重试` : ""}</p>}<div className="scope-tabs"><button className={mode === "recent" ? "active" : ""} onClick={() => changeMode("recent")}><b>最近场次分析</b><span>寻找跨场趋势和重复问题</span></button><button className={mode === "match" ? "active" : ""} onClick={() => changeMode("match")}><b>单局比赛复盘</b><span>选定一场比赛深入分析</span></button></div>{mode === "match" && <div className="match-picker"><header><b>选择一场最近的竞技比赛</b><span>{matches.length} 场可选</span></header><div>{matches.map((item) => <button key={item.matchId} className={selectedMatchId === item.matchId ? "active" : ""} onClick={() => setSelectedMatchId(item.matchId)}><span><b>{item.mapName}</b><small>{formatMatchDate(item.playedAt)}</small></span><em className={item.result}>{item.result === "win" ? "胜利" : "失利"}</em></button>)}</div></div>}<div className="question-panel"><div className="scope-note"><b>{mode === "recent" ? "分析最近完成的竞技场次" : `${selectedMatch?.mapName ?? "所选比赛"} · 单局范围`}</b><span>{mode === "recent" ? "Agent 可比较趋势、地图、攻守和首死问题" : "Agent 不会混入其他比赛数据"}</span></div><label htmlFor="question">你想复盘什么？</label><div className="composer"><textarea id="question" value={question} onChange={(event) => setQuestion(event.target.value)} rows={2} /><button className="primary" disabled={loading || !question.trim() || (mode === "match" && !selectedMatchId)} onClick={analyze}>{loading ? "分析中…" : "开始分析"}<b>↗</b></button></div><div className="presets">{presets.map((preset) => <button className={question === preset.question ? "active" : ""} key={preset.label} onClick={() => setQuestion(preset.question)}>{preset.label}</button>)}</div></div></>}{error && <div className="error"><div><b>请求未完成</b><p>{error}</p></div><button onClick={loggedIn ? syncMatches : demoLogin} disabled={loading}>重试</button></div>}</section>
    {loggedIn && <section className="product-panels"><article><header><b>同段位基准</b><span>去标识化聚合</span></header>{benchmark?.available && benchmark.median ? <><p>当前段位样本：{benchmark.cohortPlayers} 名玩家</p><div className="benchmark-grid"><span>K/D <b>{benchmark.player?.kd.toFixed(2)} / {benchmark.median.kd.toFixed(2)}</b></span><span>ADR <b>{benchmark.player?.adr.toFixed(1)} / {benchmark.median.adr.toFixed(1)}</b></span><span>ACS <b>{benchmark.player?.acs.toFixed(1)} / {benchmark.median.acs.toFixed(1)}</b></span></div></> : <p>{benchmark?.limitation ?? "正在读取基准可用性。"}</p>}<small>仅在满足最小样本门槛时显示群体结论。</small></article><article><header><b>训练记忆</b><span>只属于当前账号</span></header><div className="memory-create"><select value={memoryKind} onChange={(event) => setMemoryKind(event.target.value as Memory["kind"])}><option value="goal">训练目标</option><option value="summary">分析摘要</option></select><input value={memoryDraft} onChange={(event) => setMemoryDraft(event.target.value)} placeholder="例如：本周专注减少无信息首死" maxLength={2000} /><button onClick={addMemory}>保存</button></div>{memories.map((memory) => <div className="memory-item" key={memory.id}><select value={memory.kind} onChange={(event) => setMemories((items) => items.map((item) => item.id === memory.id ? { ...item, kind: event.target.value as Memory["kind"] } : item))}><option value="goal">目标</option><option value="summary">摘要</option></select><textarea value={memory.content} onChange={(event) => setMemories((items) => items.map((item) => item.id === memory.id ? { ...item, content: event.target.value } : item))} /><button onClick={() => editMemory(memory)}>更新</button><button onClick={() => deleteMemory(memory.id)}>删除</button></div>)}</article></section>}
    {loggedIn && <p className="legal-links"><a href="/privacy">隐私政策</a><a href="/terms">服务条款</a><a href="/data-deletion">数据删除</a> · Riot Games 第三方免责声明</p>}
    {result?.answer.nextQuestions.length ? <section className="follow-ups"><small>继续追问</small><div>{result.answer.nextQuestions.map((item) => <button key={item} onClick={() => continueQuestion(item)}>{item}<b>↗</b></button>)}</div></section> : null}
    {result && <section className="results"><header><div><i />分析结果</div><span>{mode === "recent" ? "最近场次" : selectedMatch?.mapName ?? "单局比赛"}</span></header><div className="analysis-summary"><article><small>核心结论</small><h2>{result.answer.conclusion}</h2></article><aside><span>{result.answer.playerEvidence.length}<small>证据条目</small></span><span>{result.answer.recommendations.length}<small>行动建议</small></span></aside></div><section className="evidence-list"><header><b>关键证据</b><span>指标与比赛 / 回合引用</span></header>{result.answer.playerEvidence.length ? result.answer.playerEvidence.map((item, index) => <article key={`${item.claim}-${index}`}><i>{String(index + 1).padStart(2, "0")}</i><p><b>{item.claim}</b><span>{item.metricName ?? `${item.matchId} · 第 ${item.roundNumber} 回合`}</span></p></article>) : <p>当前没有足够的个人比赛证据。</p>}</section><section className="recommendations"><header><b>下一步怎么练</b></header>{result.answer.recommendations.map((item, index) => <article key={`${item.action}-${index}`}><i>{index + 1}</i><p><b>{item.action}</b><span>{item.rationale}</span></p></article>)}</section><div className="details"><section><small>数据限制</small>{result.answer.limitations.map((item) => <p key={item}>— {item}</p>)}</section></div><div className="trace"><div><small>运行诊断</small><b>{trace ? `${trace.status.toUpperCase()} · ${trace.steps} STEPS · ${trace.toolNames.join(" / ") || "NO TOOL"}` : `RUN ${result.runId.slice(0, 8)} · ${result.usage?.totalTokens ?? 0} TOKENS`}</b></div><button onClick={loadTrace}>{trace ? "已加载" : "展开 Trace"}</button></div></section>}
    {result && <div className="save-summary-bar"><button className="secondary" disabled={savingSummary || savedSummaryRunId === result.runId} onClick={saveAnalysisSummary}>{savedSummaryRunId === result.runId ? "已保存到训练记忆" : savingSummary ? "保存中…" : "保存本次分析为训练摘要"}</button></div>}
    {loggedIn && <div className="account-disconnect"><button className="secondary" disabled={loading} onClick={disconnectAccount}>断开账号并删除关联数据</button></div>}
  </main>;
}
