"use client";
import { useState } from "react";

type Evidence = { claim: string; metricName?: string; matchId?: string; roundNumber?: number };
type Answer = { conclusion: string; confidence: "low" | "medium" | "high"; playerEvidence: Evidence[]; recommendations: Array<{ action: string; rationale: string }>; limitations: string[]; nextQuestions: string[] };
type Usage = { inputTokens: number; outputTokens: number; totalTokens: number; estimatedCostUsd: number | null };
type Result = { runId: string; answer: Answer; usage?: Usage };
type Trace = { status: string; steps: number; toolNames: string[]; usage: Usage };
const presets = [{ label: "攻守差异", question: "我的攻守方表现有什么差异？" }, { label: "近期趋势", question: "我最近的趋势如何？" }, { label: "首死复盘", question: "我为什么经常成为首死？" }, { label: "Haven 表现", question: "我在 Haven 的表现如何？" }];
const confidenceLabel = (value: Answer["confidence"]) => value === "high" ? "高置信度" : value === "medium" ? "中等置信度" : "低置信度";

export function AgentDemo() {
  const [loggedIn, setLoggedIn] = useState(false); const [question, setQuestion] = useState(presets[0].question);
  const [result, setResult] = useState<Result | null>(null); const [trace, setTrace] = useState<Trace | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function demoLogin() { setLoading(true); setError(null); const response = await fetch("/api/auth/demo", { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); setLoading(false); if (!response.ok) return setError((await response.json()).message ?? "Demo 登录失败"); setLoggedIn(true); }
  async function analyze() { setLoading(true); setError(null); setResult(null); setTrace(null); const response = await fetch("/api/agent/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question }) }); const payload = await response.json(); setLoading(false); if (!response.ok) return setError(payload.message ?? "分析失败，请重试。"); setResult(payload); }
  async function loadTrace() { if (!result) return; const response = await fetch(`/api/agent/runs/${result.runId}`); const payload = await response.json(); if (!response.ok) return setError(payload.message ?? "无法读取本次运行记录。"); setTrace(payload); }
  return <main className="app-shell"><nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">V</span>VALORANT <em>ANALYTICS</em></a><span className="mode"><i />POST-MATCH ANALYSIS</span></nav>
    <section className="hero" id="top"><div><p className="eyebrow">个人竞技复盘 · DEMO</p><h1>把每一场<br /><b>复盘成下一场优势。</b></h1><p>从结构化赛后指标和具体回合证据出发，生成能追溯、可执行的训练建议。</p><div className="chips"><span>仅本人数据</span><span>仅竞技赛后</span><span>证据可回溯</span></div></div><aside><small>AGENT STATUS</small><strong>{loggedIn ? "READY" : "STANDBY"}</strong><p>{loggedIn ? "已连接固定 Demo 账号" : "登录后开始你的赛后分析"}</p></aside></section>
    <section className="workspace"><header><span>01</span><div><h2>发起复盘</h2><p>选择方向，或直接描述你想回看的问题。</p></div></header>{!loggedIn ? <div className="login-panel"><div><small>DEMO FIXTURE</small><h3>准备分析你的竞技记录</h3><p>使用服务器固定的脱敏账号，不接收玩家 ID、PUUID 或 Riot 凭据。</p></div><button className="primary" disabled={loading} onClick={demoLogin}>{loading ? "正在连接…" : "登录 Demo 账号"} <b>→</b></button></div> : <div className="question-panel"><div className="presets">{presets.map((preset) => <button className={question === preset.question ? "active" : ""} key={preset.label} onClick={() => setQuestion(preset.question)}>{preset.label}</button>)}</div><label htmlFor="question">你的问题</label><textarea id="question" value={question} onChange={(event) => setQuestion(event.target.value)} rows={4} /><footer><p>模型只可访问当前会话的竞技赛后结构化数据。</p><button className="primary" disabled={loading || !question.trim()} onClick={analyze}>{loading ? "Agent 分析中…" : "开始分析"} <b>↗</b></button></footer></div>}{error && <div className="error"><div><b>请求未完成</b><p>{error}</p></div><button onClick={loggedIn ? analyze : demoLogin} disabled={loading}>重试</button></div>}</section>
    {result && <section className="results"><header><span>02</span><div><h2>分析结果</h2><p>结论来自可查询的结构化指标或比赛/回合记录。</p></div></header><article className="conclusion"><div><em className={result.answer.confidence}>{confidenceLabel(result.answer.confidence)}</em><small>RUN · {result.runId.slice(0, 8)}</small></div><h2>{result.answer.conclusion}</h2><footer><span>{result.usage?.totalTokens ?? 0} TOKENS</span><span>{result.answer.playerEvidence.length} EVIDENCE ITEMS</span><span>{result.answer.recommendations.length} ACTIONS</span></footer></article><div className="result-grid"><section><small>EVIDENCE / 证据</small>{result.answer.playerEvidence.length ? <ul>{result.answer.playerEvidence.map((item, index) => <li key={`${item.claim}-${index}`}><i>{String(index + 1).padStart(2, "0")}</i><div><b>{item.claim}</b><p>{item.metricName ?? `${item.matchId} · 第 ${item.roundNumber} 回合`}</p></div></li>)}</ul> : <p>当前没有可引用的个人证据。</p>}</section><section className="actions"><small>NEXT ACTIONS / 建议</small><ul>{result.answer.recommendations.map((item, index) => <li key={`${item.action}-${index}`}><i>↗</i><div><b>{item.action}</b><p>{item.rationale}</p></div></li>)}</ul></section></div><div className="details"><section><small>LIMITATIONS / 限制</small>{result.answer.limitations.map((item) => <p key={item}>— {item}</p>)}</section><section><small>FOLLOW UPS / 下一步</small>{result.answer.nextQuestions.map((item) => <p key={item}>— {item}</p>)}</section></div><div className="trace"><div><small>RUN DIAGNOSTICS</small><b>{trace ? `${trace.status.toUpperCase()} · ${trace.steps} STEPS` : "本次运行记录已安全保存"}</b><p>{trace ? `工具：${trace.toolNames.join(" · ") || "无"}` : "Trace 仅对当前会话用户可见，不包含 Prompt、原始工具数据或服务端密钥。"}</p></div><button onClick={loadTrace}>{trace ? "已加载" : "查看 Trace"}</button></div></section>}
  </main>;
}
